import type {
  Claim,
  Communication,
  Customer,
  Task,
  TimelineEvent,
} from "./types";

export const customers: Customer[] = [
  {
    id: "cus-001",
    company: "Timberline Outdoor Supply",
    contact: "Maya Chen",
    email: "maya@timberlineoutdoor.com",
    phone: "(970) 555-0148",
    address: "1280 Canyon View Rd",
    city: "Fort Collins",
    state: "CO",
    status: "Renewal",
    source: "Analyzer",
    assignedAgent: "Alex Morgan",
    csr: "Jordan Lee",
    healthScore: 78,
    estimatedPremium: 48200,
    renewalDate: "2026-08-18",
    industry: "Outdoor Retail",
    tags: ["Key Account", "Multi-policy"],
    lastContact: "2026-07-02T15:40:00",
    policies: [
      {
        id: "pol-001",
        type: "Business Owners Policy",
        carrier: "Travelers",
        policyNumber: "BOP-884201",
        premium: 28600,
        deductible: 2500,
        effective: "2025-08-18",
        expiration: "2026-08-18",
        status: "Active",
      },
      {
        id: "pol-002",
        type: "Commercial Auto",
        carrier: "Progressive",
        policyNumber: "CA-442981",
        premium: 19600,
        deductible: 1000,
        effective: "2025-08-18",
        expiration: "2026-08-18",
        status: "Active",
      },
    ],
  },
  {
    id: "cus-002",
    company: "Juniper Ridge Dental",
    contact: "Dr. Elena Ruiz",
    email: "elena@juniperridgedental.com",
    phone: "(303) 555-0181",
    address: "4400 W 38th Ave",
    city: "Denver",
    state: "CO",
    status: "Current",
    source: "Referral",
    assignedAgent: "Sam Patel",
    csr: "Jordan Lee",
    healthScore: 92,
    estimatedPremium: 31750,
    renewalDate: "2026-11-03",
    industry: "Dental Practice",
    tags: ["Referral", "High retention"],
    lastContact: "2026-06-29T11:15:00",
    policies: [
      {
        id: "pol-003",
        type: "Professional Liability",
        carrier: "CNA",
        policyNumber: "PL-229184",
        premium: 31750,
        deductible: 5000,
        effective: "2025-11-03",
        expiration: "2026-11-03",
        status: "Active",
      },
    ],
  },
  {
    id: "cus-003",
    company: "Bluebird Coffee Roasters",
    contact: "Theo Wilson",
    email: "theo@bluebirdroasters.com",
    phone: "(720) 555-0133",
    address: "1918 Market St",
    city: "Denver",
    state: "CO",
    status: "Quoted",
    source: "Website",
    assignedAgent: "Alex Morgan",
    csr: "Taylor Reed",
    healthScore: 64,
    estimatedPremium: 22400,
    renewalDate: "2026-09-12",
    industry: "Food Manufacturing",
    tags: ["Hot lead"],
    lastContact: "2026-06-25T09:30:00",
    policies: [],
  },
  {
    id: "cus-004",
    company: "Red Peak Construction",
    contact: "Marcus Hill",
    email: "marcus@redpeakco.com",
    phone: "(719) 555-0192",
    address: "78 Mesa Industrial Way",
    city: "Colorado Springs",
    state: "CO",
    status: "Application",
    source: "Discovery",
    assignedAgent: "Sam Patel",
    csr: "Taylor Reed",
    healthScore: 71,
    estimatedPremium: 87500,
    renewalDate: "2026-10-01",
    industry: "Commercial Construction",
    tags: ["High premium", "WC opportunity"],
    lastContact: "2026-07-01T14:00:00",
    policies: [],
  },
  {
    id: "cus-005",
    company: "Sage & Stone Design",
    contact: "Priya Shah",
    email: "priya@sageandstone.co",
    phone: "(970) 555-0176",
    address: "603 Pearl St",
    city: "Boulder",
    state: "CO",
    status: "Lead",
    source: "Manual",
    assignedAgent: "Alex Morgan",
    csr: "Jordan Lee",
    healthScore: 55,
    estimatedPremium: 14800,
    renewalDate: "2026-12-14",
    industry: "Interior Design",
    tags: ["New business"],
    lastContact: "2026-06-12T16:20:00",
    policies: [],
  },
  {
    id: "cus-006",
    company: "Front Range Pediatrics",
    contact: "Nora Bennett",
    email: "nora@frpediatrics.com",
    phone: "(303) 555-0114",
    address: "8250 E Belleview Ave",
    city: "Greenwood Village",
    state: "CO",
    status: "Current",
    source: "Import",
    assignedAgent: "Sam Patel",
    csr: "Jordan Lee",
    healthScore: 88,
    estimatedPremium: 56400,
    renewalDate: "2027-01-22",
    industry: "Healthcare",
    tags: ["Key Account"],
    lastContact: "2026-07-02T10:05:00",
    policies: [
      {
        id: "pol-004",
        type: "Medical Professional Liability",
        carrier: "The Doctors Company",
        policyNumber: "MPL-703118",
        premium: 56400,
        deductible: 10000,
        effective: "2026-01-22",
        expiration: "2027-01-22",
        status: "Active",
      },
    ],
  },
  {
    id: "cus-007",
    company: "Apex Electric & Solar",
    contact: "Daniel Kim",
    email: "daniel@apexsolar.co",
    phone: "(720) 555-0167",
    address: "3100 Blake St",
    city: "Denver",
    state: "CO",
    status: "Opportunity",
    source: "Discovery",
    assignedAgent: "Unassigned",
    csr: "Unassigned",
    healthScore: 42,
    estimatedPremium: 69200,
    renewalDate: "2026-09-28",
    industry: "Electrical Contractor",
    tags: ["AI discovered"],
    lastContact: "2026-05-28T08:00:00",
    policies: [],
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    customerId: "cus-001",
    title: "Review renewal exposure changes",
    due: "2026-07-03",
    priority: "Urgent",
    assignee: "Alex Morgan",
    completed: false,
  },
  {
    id: "task-2",
    customerId: "cus-004",
    title: "Collect signed loss runs",
    due: "2026-07-03",
    priority: "High",
    assignee: "Sam Patel",
    completed: false,
  },
  {
    id: "task-3",
    customerId: "cus-003",
    title: "Follow up on BOP proposal",
    due: "2026-07-04",
    priority: "High",
    assignee: "Alex Morgan",
    completed: false,
  },
  {
    id: "task-4",
    customerId: "cus-005",
    title: "Schedule discovery call",
    due: "2026-07-06",
    priority: "Medium",
    assignee: "Alex Morgan",
    completed: false,
  },
  {
    id: "task-5",
    customerId: "cus-002",
    title: "Confirm cyber questionnaire",
    due: "2026-07-01",
    priority: "Medium",
    assignee: "Jordan Lee",
    completed: false,
  },
];

export const claims: Claim[] = [
  {
    id: "claim-1",
    customerId: "cus-001",
    number: "TRV-CL-88214",
    type: "Property",
    carrier: "Travelers",
    status: "Waiting on Carrier",
    dateOfLoss: "2026-06-14",
    updatedAt: "2026-06-26",
    adjuster: "Rita Douglas",
    reserve: 24000,
  },
  {
    id: "claim-2",
    customerId: "cus-006",
    number: "TDC-CL-11082",
    type: "Professional Liability",
    carrier: "The Doctors Company",
    status: "Investigation",
    dateOfLoss: "2026-05-18",
    updatedAt: "2026-07-01",
    adjuster: "Micah Stone",
    reserve: 85000,
  },
  {
    id: "claim-3",
    customerId: "cus-002",
    number: "CNA-CL-50991",
    type: "Equipment Breakdown",
    carrier: "CNA",
    status: "Closed",
    dateOfLoss: "2026-02-03",
    updatedAt: "2026-04-16",
    adjuster: "June Ford",
    reserve: 9200,
  },
];

export const communications: Communication[] = [
  {
    id: "com-1",
    customerId: "cus-001",
    channel: "Email",
    direction: "inbound",
    author: "Maya Chen",
    body: "I uploaded the updated inventory schedule. We also added a second delivery van last month—does that change what you need for renewal?",
    timestamp: "2026-07-02T15:40:00",
    unread: true,
  },
  {
    id: "com-2",
    customerId: "cus-001",
    channel: "Call",
    direction: "outbound",
    author: "Alex Morgan",
    body: "18 min call. Reviewed property claim status and agreed to include the new Boulder pop-up location in the renewal review.",
    timestamp: "2026-06-30T10:15:00",
  },
  {
    id: "com-3",
    customerId: "cus-001",
    channel: "Note",
    direction: "internal",
    author: "Jordan Lee",
    body: "Travelers requested updated values and five-year loss runs. Inventory schedule received; loss runs still outstanding.",
    timestamp: "2026-06-27T14:22:00",
  },
  {
    id: "com-4",
    customerId: "cus-004",
    channel: "SMS",
    direction: "inbound",
    author: "Marcus Hill",
    body: "I can send payroll by class code this afternoon. Still waiting on the current carrier for loss runs.",
    timestamp: "2026-07-03T08:38:00",
    unread: true,
  },
  {
    id: "com-5",
    customerId: "cus-003",
    channel: "Email",
    direction: "outbound",
    author: "Alex Morgan",
    body: "Theo, I’ve attached the two options we discussed. The Travelers proposal offers the stronger spoilage limit.",
    timestamp: "2026-07-02T11:08:00",
  },
];

export const timeline: TimelineEvent[] = [
  {
    id: "ev-1",
    customerId: "cus-001",
    type: "Document",
    title: "Inventory schedule uploaded",
    detail: "2026 Inventory Schedule.xlsx added by Maya Chen",
    timestamp: "2026-07-02T15:39:00",
  },
  {
    id: "ev-2",
    customerId: "cus-001",
    type: "Communication",
    title: "Email received from Maya Chen",
    detail: "Renewal exposure update and new vehicle disclosed",
    timestamp: "2026-07-02T15:40:00",
  },
  {
    id: "ev-3",
    customerId: "cus-001",
    type: "Claim",
    title: "Claim moved to Waiting on Carrier",
    detail: "Updated by Jordan Lee",
    timestamp: "2026-06-26T12:10:00",
  },
  {
    id: "ev-4",
    customerId: "cus-001",
    type: "Policy",
    title: "Renewal workflow started",
    detail: "120-day renewal sequence enrolled automatically",
    timestamp: "2026-04-20T09:00:00",
  },
];

export const discovery = [
  {
    id: "opp-1",
    company: "Apex Electric & Solar",
    contact: "Daniel Kim",
    type: "Workers Compensation Review",
    score: 94,
    premium: 69200,
    reason: "Rapid hiring and multi-state project growth",
    source: "Public business data",
  },
  {
    id: "opp-2",
    company: "Canyon Creek Hospitality",
    contact: "Amelia Ross",
    type: "Policy Expiring Soon",
    score: 88,
    premium: 118000,
    reason: "Renewal estimated within 75 days",
    source: "Imported prospect list",
  },
  {
    id: "opp-3",
    company: "Northstar Robotics",
    contact: "Ben Okafor",
    type: "Cyber Coverage Gap",
    score: 84,
    premium: 42600,
    reason: "Technology profile with no cyber filing signal",
    source: "Google Business",
  },
];
